apiVersion: v1
kind: Service
metadata:
  name: apirest
  namespace: default
  labels:
    app: nodejs
spec:
  type: LoadBalancer 
  ports:
    - port: 3010
  selector:
      app: nodejs
      tier: api
  externalIPs:
    - 192.168.49.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apirest
  namespace: default
  labels:
    app: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
      tier: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodejs
        tier: api
    spec:
      containers:
      - image: juanes240899/microservice-api:latest
        name: api
        ports:
        - containerPort: 3010
          name: api
