#*****************NameSpace****************#
---
apiVersion: v1
kind: Namespace
metadata:
  name: sensores
#*****************DataBase*****************#
#Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: sensores
  labels:
    app: bd
spec:
  type: ClusterIP 
  ports:
    - name: "3306"
      port: 3306
  selector:
      app: bd
      tier: mysql
---
#Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-claim
  namespace: sensores
  labels:
    app: bd
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/home/heberth/volumen"

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: sensores
  labels:
    app: bd
spec:
  selector:
    matchLabels:
      app: bd
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bd
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "ROOT2021"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          hostPath:
            path: /home/heberth/volumen
            
---
#*****************ApiRest*****************#
#Service
apiVersion: v1
kind: Service
metadata:
  name: apirest
  namespace: sensores
  labels:
    app: nodejs
spec:
  type: NodePort 
  ports:
    - name: "3010"
      port: 3010
  selector:
      app: nodejs
      tier: api
---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apirest
  namespace: sensores
  labels:
    app: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
      tier: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodejs
        tier: api
    spec:
      containers:
      - image: juanes240899/apisensores:1.3
        name: api
        env:
        - name: PORT_SERVER
          value: "3010"
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASS
          value: "ROOT2021"
        - name: MYSQL_DATABASE
          value: "modulos_sensores"
        - name: TOKEN_KEY
          value: "m4w351545d3v3l0p50f7w4r3s1nc32014"
        - name: TOKEN_EXPIRE_IN
          value: "300"
        - name: TOKEN_KEY_DEVICES
          value: "m4w351545d3v3l0p50f7w4r3s1nc32014nshwn85475ynsys922"
        - name: TOKEN_EXPIRE_IN_DISPOSITIVO
          value: "31536000"
        - name: AUTHENTICATION
          value: "false"
        - name: MQTT_HOST
          value: "maqiatto.com"
        - name: MQTT_CLIENT_ID
          value: "clientId-PQQtMLRjX6"
        - name: MQTT_USERNAME
          value: "sensores.rescity@gmail.com"
        - name: MQTT_PASSWORD
          value: "R35Ci1tyzozi"
        - name: MQTT_TOPIC_NOTIFICACIONS
          value: "sensores.rescity@gmail.com/SensorsReport"
        - name: MAIL_USER
          value: "sensores.rescity@gmail.com"
        - name: MAIL_PASSWORD
          value: "R35Ci1tyzozi"
        - name: IMG_CORREO
          value: "https://pattern.uao.edu.co/images/UAO-logo-acreditacion.png"  
        - name: KAFKA_BROKER
          value: "127.0.0.1:9092"  
        - name: KAFKA_CLIENT_ID
          value: "53n30r35"  
        - name: KAFKA_TOPIC
          value: "SensoresTopic"  
        - name: KAFKA_kEY
          value: "SensorsReport"  
        ports:
        - containerPort: 3010
          name: api

